
import React, { useState, useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Drawer, DrawerContent, DrawerTrigger } from "@/components/ui/drawer";
import { Menu, Search, ShieldAlert, UtensilsCrossed, ChevronLeft, LogIn, LogOut, Users, FileText, RefreshCw, History, LayoutDashboard } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { AdminLoginDialog } from "@/components/admin/AdminLoginDialog";
import { useAdminAuth } from "@/hooks/use-admin-auth";
import { MenuDay } from "@/components/admin/menu-editor/types";
import { weeklyMenu } from "@/data/menuData";
import { useIsMobile } from "@/hooks/use-mobile";
import { UserTable } from "@/components/admin/UserTable";
import { OrdersTable } from "@/components/admin/OrdersTable";
import { OrderItemsTable } from "@/components/admin/OrderItemsTable";
import { ArticlesManager } from "@/components/admin/articles/ArticlesManager";
import { MenuEditor } from "@/components/admin/menu-editor/MenuEditor";
import { HomepageEditor } from "@/components/admin/homepage-editor/HomepageEditor";
import { AdminRoleManager } from "@/components/admin/AdminRoleManager";
import { useRoleBasedAccess } from "@/hooks/use-role-based-access";
import { AccessDenied } from "@/components/admin/AccessDenied";
import { AuditLogViewer } from "@/components/admin/AuditLogViewer";
import { StatCard } from "@/components/admin/stats/StatCard";
import { DashboardStats } from "@/components/admin/stats/DashboardStats";
import { logAdminAction } from "@/integrations/supabase/client";
