import { randomInt } from "node:crypto";

/**
 * Human-readable order reference, generated by the server.
 *
 * The legacy client built this in the browser from `Date.now()` and
 * `Math.random()`, which let two tabs collide and let anyone predict the next
 * value. The random half now comes from the CSPRNG, and the database's unique
 * index on `receipt_id` is the final arbiter.
 */
export function generateReceiptId(now: Date = new Date()): string {
  const stamp = now.toISOString().slice(2, 10).replace(/-/g, "");
  const random = randomInt(0, 1_000_000).toString().padStart(6, "0");
  return `CMD-${stamp}-${random}`;
}
