
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqukhginnbwuqrejhlsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxdWtoZ2lubmJ3dXFyZWpobHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTgzNTUsImV4cCI6MjA2MDAzNDM1NX0.-yB90sffHThPfh8dwwNpiCZCUbr2syv7rZWO6_7w2cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

/**
 * Checks if a user has the admin role in the database
 * @param userId User ID to check
 * @returns Promise resolving to boolean
 */
export const isAdminUser = async (userId: string): Promise<boolean> => {
  try {
    // Call the RPC function to check if the user has the admin role
    const { data, error } = await supabase.rpc('has_role', {
      user_id: userId,
      required_role: 'admin'
    });

    if (error) {
      console.error("Error checking admin role:", error);
      return false;
    }

    return !!data;
  } catch (error) {
    console.error("Exception checking admin role:", error);
    return false;
  }
};
