
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/database.types';

const SUPABASE_URL = "https://cteafpapifodqvzojbjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0ZWFmcGFwaWZvZHF2em9qYmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDkzNDcsImV4cCI6MjA2MTAyNTM0N30.v6tfgF6x-KfhxqroQu3MlDVcnq2yrOkIKLqGwqDl7cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// User role constants - use these instead of just the type
export const AdminRoleType = {
  ADMIN: 'admin',
  ORDER_MANAGER: 'order_manager', 
  VIEWER: 'viewer'
} as const;

export type AdminRoleType = typeof AdminRoleType[keyof typeof AdminRoleType];

/**
 * Checks if a user has a specific role
 */
export const hasUserRole = async (userId: string, role: AdminRoleType): Promise<boolean> => {
  try {
    const { data, error } = await supabase
      .from('user_roles')
      .select('*')
      .eq('user_id', userId)
      .eq('role', role)
      .maybeSingle();
      
    if (error) {
      console.error("Error checking user role:", error);
      return false;
    }
    
    return !!data;
  } catch (error) {
    console.error("Exception checking user role:", error);
    return false;
  }
};

/**
 * Checks if a user is an admin
 */
export const isAdminUser = async (userId: string): Promise<boolean> => {
  return await hasUserRole(userId, AdminRoleType.ADMIN);
};

/**
 * Logs an admin action in the audit log
 */
export const logAdminAction = async (
  userId: string,
  action: string,
  resource: string,
  details?: any
): Promise<void> => {
  try {
    const { error } = await supabase
      .from('admin_audit_log')
      .insert({
        user_id: userId,
        action,
        resource,
        details
      });
      
    if (error) {
      console.error("Error logging admin action:", error);
    }
  } catch (error) {
    console.error("Exception logging admin action:", error);
  }
};
